<template>
    <div class="example-3__wrapper" ref="wrapperRef">
        <div ref="titleWrapperRef" class="title__wrapper">
            <WaterflowTitle :show="true"></WaterflowTitle>
        </div>

        <div class="content" ref="contentRef">

            <div class="text">
                Introducing Waterflow - the new VueJS library for beautiful and seamless page transitions! Waterflow is
                designed to make your VueJS projects more engaging and user-friendly by providing you with a simple and
                customizable way to create stunning page transitions. With Waterflow, you can easily add fluid,
                waterfall-like animations to your website that will keep your users engaged and excited about exploring your
                content.
                Here are just a few of the features that Waterflow offers: Easy to use: With a simple and intuitive API,
                Waterflow is easy to add to your VueJS project and start creating beautiful page transitions right away.
                Customizable animations: Choose from a variety of built-in animation styles or create your own custom
                animations to match your website's branding and style. Cross-browser compatibility: Waterflow is designed to
                work seamlessly across all major web browsers, so you can be confident that your users will have a
                consistent experience no matter what browser they're using. Seamless integration: Waterflow integrates
                easily with other VueJS libraries and frameworks, so you can use it alongside your existing codebase without
                any issues. Whether you're building a blog, a portfolio, or an e-commerce site, Waterflow has the tools you
                need to create stunning page transitions that will set your website apart. Try it out today and take your
                VueJS project to the next level! This text is obviously generated by chatgpt.
            </div>
            <div class="return">
                <ReturnButton />
            </div>
        </div>
    </div>
</template>

<script lang="ts" setup>
import { onFlow, useFlowProvider, usePageFlow } from '~/../index';
import { N } from '~/helpers/namhai-utils';

const wrapperRef = ref()
const contentRef = ref()
const titleWrapperRef = ref()

const flowProvider = useFlowProvider()
const { $TL, $lenis } = useNuxtApp()

onMounted(() => {
    $lenis.dimensions.onWindowResize()
    $lenis.dimensions.onContentResize()
})


usePageFlow({
    props: { wrapperRef, contentRef, titleWrapperRef },
    enableCrossfade: 'BOTTOM',
    flowInCrossfade: ({ }, resolve) => {
        let tl = new $TL
        tl.from({
            el: wrapperRef.value,
            d: 800,
            p: {
                x: [100, 0],
            },
            e: 'io4',
            cb: () => {
                resolve()
            }
        })
        tl.play()
    },
    flowOut: async ({ }, resolve) => {
        let tl = new $TL
        const { $canvas } = useNuxtApp()
        $canvas.onChange(flowProvider.getRouteTo())
        await $canvas.nextCanvasPage?.init()
        $canvas.currentCanvasPage?.destroy()
        $canvas.currentCanvasPage = $canvas.nextCanvasPage

        tl.from({
            el: wrapperRef.value,
            d: 800,
            p: {
                x: [0, -100],
            },
            e: 'io4',
            cb: async () => {
                resolve()
            }
        })
        tl.play()
    }
})
</script>

<style scoped lang="scss">
@use "@/styles/shared.scss" as *;
@use "@/styles/app/variables.scss" as *;

.example-3__wrapper {
    position: absolute;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    background-color: #FFF27A;

    color: #46afff;
    display: flex;
    flex-direction: column;
    overflow: hidden;
}

.title__wrapper {
    position: relative;
}

.title-container {
    left: 50%;
    position: absolute;
    transform: translateX(-50%);
}

.content {
    padding: 2.4rem 0rem 4rem;
    margin: $title-height auto 0;
    display: flex;
    height: 100%;
    width: 151.4rem;
    flex-direction: column;

    @include breakpoint(mobile) {
        width: 32rem;
        min-height: calc(100% - 4rem);
        margin: $title-height-mobile auto 0;
    }

    .text {
        font-size: 3rem;
        font-weight: 800;
        color: #FFFB8F;
        text-transform: uppercase;

        @include breakpoint(mobile) {
            font-size: 1rem;
        }
    }
}

.return {
    margin-top: auto;
}
</style>
